# Generated by Django 3.0.5 on 2021-06-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_purchase',
            name='invoiceDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 24, 49, 994922)),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 24, 49, 992921)),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='invoiceDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 24, 49, 993921)),
        ),
    ]
