# Generated by Django 3.0.5 on 2021-06-01 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210601_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_member',
            name='memberId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_member',
            name='phoneNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_purchase',
            name='invoiceDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 25, 26, 779169)),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 25, 26, 777168)),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='invoiceDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 1, 8, 25, 26, 778168)),
        ),
    ]
